[package]
name = "invenio"
version = "0.1.0"
edition = "2021"

[dependencies]
rusoto_core = "0.47"
rusoto_credential = "0.47"
rusoto_ec2 = "0.47"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2.3"
sysinfo = "0.25"

[dev-dependencies]
criterion = "0.8.1"
